apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: wiz-app
  source:
    repoURL: https://github.com/henrikfrech/devsecops-enigma.git
    targetRevision: HEAD
    path: gitops/rendered
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
